server:
  port: 8081
grpc:
  server:
    port: 9091
spring:
  application:
    name: grpc-client
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        service-name: ${spring.application.name} # 服务名称
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /actuator/health # 健康检查路径
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} # 应用名称+服务器IP+端口